# Qwen2.5-Math-1.5B-Instruct: main small model.

export DEEPSPEED_CONFIG="${DEEPSPEED_CONFIG:-configs/grpo/ds_config_zero2_no_offload.json}"

export GRPO_BATCH_SIZE="${GRPO_BATCH_SIZE:-64}"
export GRPO_GRAD_ACCUM="${GRPO_GRAD_ACCUM:-1}"
export GRPO_NUM_GENERATIONS="${GRPO_NUM_GENERATIONS:-8}"
export GRPO_MAX_PROMPT_LENGTH="${GRPO_MAX_PROMPT_LENGTH:-1024}"
export GRPO_MAX_COMPLETION_LENGTH="${GRPO_MAX_COMPLETION_LENGTH:-1024}"

export QAT_BATCH_SIZE="${QAT_BATCH_SIZE:-4}"
export QAT_GRAD_ACCUM="${QAT_GRAD_ACCUM:-8}"
export QAT_MAX_PROMPT_LENGTH="${QAT_MAX_PROMPT_LENGTH:-512}"
export QAT_MAX_NEW_TOKENS="${QAT_MAX_NEW_TOKENS:-1024}"

export EVAL_BATCH_SIZE="${EVAL_BATCH_SIZE:-64}"