# Qwen3-8B: large-model run. Uses CPU optimizer offload by default.

export DEEPSPEED_CONFIG="${DEEPSPEED_CONFIG:-configs/grpo/ds_config_zero2_qwen3_8b.json}"

export GRPO_BATCH_SIZE="${GRPO_BATCH_SIZE:-8}"
export GRPO_GRAD_ACCUM="${GRPO_GRAD_ACCUM:-8}"
export GRPO_NUM_GENERATIONS="${GRPO_NUM_GENERATIONS:-8}"
export GRPO_MAX_PROMPT_LENGTH="${GRPO_MAX_PROMPT_LENGTH:-1024}"
export GRPO_MAX_COMPLETION_LENGTH="${GRPO_MAX_COMPLETION_LENGTH:-1024}"

export QAT_BATCH_SIZE="${QAT_BATCH_SIZE:-1}"
export QAT_GRAD_ACCUM="${QAT_GRAD_ACCUM:-16}"
export QAT_MAX_PROMPT_LENGTH="${QAT_MAX_PROMPT_LENGTH:-512}"
export QAT_MAX_NEW_TOKENS="${QAT_MAX_NEW_TOKENS:-1024}"

export EVAL_BATCH_SIZE="${EVAL_BATCH_SIZE:-16}"